### ISSUE TITLE
How do you send voice_request?

### ISSUE THREAD

**Issue by echan00** [api-ai/api-ai-ruby#10]
I tried sending a voice_request as per the documentation:

`response = client.voice_request URL`

But am receiving an error:

`Errno::ENOENT: No such file or directory @ rb_sysopen`

The URL I am using is a voice file from Facebook Messenger:
https://cdn.fbsbx.com/v/t59.3654-21/16372097_10101224339745185_8021891159552950272_n.aac/audioclip-1486146157675-1101.aac?oh=c45d7b1e8664a3b418da372b25a11c20&oe=589680B4

**Comment by Gugic** [comment]
It's not for URL, it should be an instance of http://ruby-doc.org/core-2.4.0/File.html

Example from specs: client.voice_request(File.new(fixture_path + '/hello.wav'))

**Comment by echan00** [comment]
This is what I am receiving now.. is this correct?

`ApiAiRuby::RequestError: API.AI speech recognition is going to be deprecated soon. Use Google Cloud Speech API or other solutions.`

**Comment by Gugic** [comment]
Yes, this is not problem of SDK, the answer is from API.AI server itself. 

You can ask questions about platform on official API.AI forum (https://discuss.api.ai/)

**Comment by echan00** [comment]
So should I be looking at using Google Cloud Speech API instead? Now I'm just confused...

**Comment by Gugic** [comment]
The current version of ASR is currently available only to the old paid plan accounts. We are planning to update our SDKs and documentation soon. Stay tuned.

**Comment by echan00** [comment]
What is ASR? 

Is it not possible to tell me what you plan to do (and what you suggest) so I can also plan ahead? 

You could have told me speech is being depreciated from the get go instead of linking to the Ruby file class in the first place :(

**Comment by Gugic** [comment]
ASR is short for 'speech recognition'. API.AI ASR is still available on paid plans  (as i mentioned before) and i don't know if you have one, so i just answer a question.

For now we suggest using 3rd-party speech recognition service (e.g. Google Speech).

In the future there probably will be some additional helper classes that automates communications between 3rd party speech recognition service and API.AI.

**Comment by echan00** [comment]
OK thanks!
