### ISSUE TITLE
error updating  a user entity

### ISSUE THREAD

**Issue by pchowdhry** [api-ai/api-ai-ruby#11]
Hi I have an entity created through the ui called @accounts. I'm assuming there is no difference between a developer entity and user entity (I couldn't find any in the documentation). I'm trying to update the values of that entity on a session basis (dynamic accounts per user).

`    client = ApiAiRuby::Client.new(
        :client_access_token => 'XXXX',
        :api_session_id => '6cd77d71-2c7b-4cfa-869d-64ac1864c6bf'
    )`

`    entries_products = [
        ApiAiRuby::Entry.new('heloc', %w(home equity line of credit)),
        ApiAiRuby::Entry.new('auto loan', %w(car loan))
    ]`

`uer = client.user_entities_request`

`uer.update('accounts', entries_products)`

when I execute this I get

`'ApiAiRuby::RequestError: UserEntity 'accounts' is not found.`

I've also tried creating the userentity

`uer.create(['accounts'])`

and I get

`ApiAiRuby::RequestError: Error adding entity.`

I'm not sure what the issue is here.....

thanks in advance

**Comment by pchowdhry** [comment]
??

**Comment by Gugic** [comment]
Hello, sorry for the late answer. 
Do you have entity 'accounts' in your agent?

**Comment by pchowdhry** [comment]
Yes, I'm able to create the entities if i do it as part of a request, but can't do it via crud...

**Comment by Gugic** [comment]
userEntitiesRequest is about https://docs.api.ai/docs/userentities API.AI endpoint, not about https://docs.api.ai/docs/entities

It is not allow you to create new entities, it allow you to extend and redefine existing. 

Error `'ApiAiRuby::RequestError: UserEntity 'accounts' is not found.` looks just like your agent has no 'accounts' entity that you are going to extend with your custom entries.

**Comment by pchowdhry** [comment]
I'll put together a full test script for you. The most up to date error i was getting wasn't that it wasn't available, but there was an error updating the entity. Once i have the script written i'll update back..

**Comment by pchowdhry** [comment]
Hi i was able to replicate the issue by the following

```
@session = '0955ef26-0d50-4375-a9b1-ffc704ece456'

client = ApiAiRuby::Client.new( :client_access_token => 'XXX', :api_session_id => @session )

uer = client.user_entities_request

entries_credit_products = [
    ApiAiRuby::Entry.new('0', %w(Home Equity Loan)),
    ApiAiRuby::Entry.new('1', %w(Starwood Visa))
]

entity_my_credit_products= ApiAiRuby::Entity.new('my_credit_products', [entries_credit_products])

uer.update('my_credit_products', entity_my_credit_products)

ApiAiRuby::RequestError: Error updating entity my_credit_products.
```

**Comment by Gugic** [comment]
@pchowdhry here you are wrapping array `entries_credit_products` in array `[entries_credit_products]` on entity creation

**Comment by pchowdhry** [comment]
so should it be

uer.update('my_credit_products', entity_my_credit_products)

?

**Comment by Gugic** [comment]
`entity_my_credit_products= ApiAiRuby::Entity.new('my_credit_products', entries_credit_products)`

**Comment by Gugic** [comment]
You also can check tests - https://github.com/api-ai/api-ai-ruby/blob/master/spec/api-ai-ruby/api_spec.rb#L71

**Comment by pchowdhry** [comment]
I tried according to you the specs which is outlined below but still get the same error.  I'm never calling  ApiAiRuby::Entity.new or @uer.create which it looks like the spec is doing. I don't believe I need to call new/create as the entity already exists. Is this correct?

```
@session = '0955ef26-0d50-4375-a9b1-ffc704ece456'

client = ApiAiRuby::Client.new( :client_access_token => 'XX', :api_session_id => @session )

uer = client.user_entities_request

entries_credit_products = [
    ApiAiRuby::Entry.new('0', %w(Home Equity Loan)),
    ApiAiRuby::Entry.new('1', %w(Starwood Visa))
]


entity_my_credit_products= ApiAiRuby::Entity.new('my_credit_products', entries_credit_products)

uer.update('my_credit_products', entity_my_credit_products)

ApiAiRuby::RequestError: Error updating entity my_credit_products.
```

**Comment by pchowdhry** [comment]
one other thing, on the SDK readme it has a line for

`uer.create(contacts) `

i don't think contacts is defined in the context of the example. Maybe that's what i'm missing?

**Comment by Gugic** [comment]
The thing is - userEntities is not the same thing as normal developer entities that you can define vie console.api.ai

To work with userEntity somehow (update/delete) you need to create it before. But to create userEntity, you need to have normal developer entity with the same name, that will be re-defined for a short period of time by your user-entity for one session.

So the correct algorithm to work with userEntities is to create it and use, and if it needed - update it.

**Comment by pchowdhry** [comment]
ok, got it. That worked. If you'd like, I'm happy to do a pull request and update the readme, to make it a little clearer, and fix the one line (uer.create(contacts)).

thanks for your help

-pankaj
