### ISSUE TITLE
Entity support

### ISSUE THREAD

**Issue by phbernard** [api-ai/api-ai-ruby#15]
As of today, the SDK supports [User Entities](https://docs.api.ai/docs/userentities) but not [Entities](https://docs.api.ai/docs/entities).

I actually needs this feature, would you be interested in a PR?

**Comment by Gugic** [comment]
First of all, thank you for your work.

We are officially suggest SDK only for "client access token" requests, not for "developer access token".

So unfortunately i can not accept your PR. I will try to merge changes connected with

**Comment by phbernard** [comment]
Alright! Thank you for your feedback.

**Comment by phbernard** [comment]
Hum... thinking about it again, could you tell me why you suggest to use the SDK with client token and not developer token? I couldn't find find any statement about this except from your message above.

I would actually be interested in using the SDK for all kind of accesses (eg. POST new intents).
