### ISSUE TITLE
Send context with parameters

### ISSUE THREAD

**Issue by jwright** [api-ai/api-ai-ruby#5]
I am trying to send parameters with a `text_request` and I cannot get the formatting correct.

I am trying:

```
client.text_request "hello", contexts: [{ name: "user", parameters: { first_name: "Johnny" }}]
```

And the response is:

```
{:id=>"XXXXX",
 :timestamp=>"2016-08-29T11:39:38.641Z",
 :result=>
  {:source=>"agent",
   :resolvedQuery=>"hello",
   :speech=>"",
   :action=>"",
   :parameters=>{},
   :contexts=>
    [{:name=>"{:name=>\"user\", :parameters=>{:first_name=>\"johnny\"}}",
      :lifespan=>4}],
   :metadata=>
    {:intentId=>"XXXXXXX",
     :webhookUsed=>"false",
     :intentName=>"salutation"},
   :score=>1.0},
 :status=>{:code=>200, :errorType=>"success"},
 :sessionId=>"XXXXX"}
```

You can see that the `contexts` holds the parameter values in the name, thus not matching them. I can get this to work over a curl post request but not through the Ruby SDK.

**Comment by Gugic** [comment]
Thank you for the report. Please, check new version, that bug should be fixed.

**Comment by jwright** [comment]
@Gugic Thank you for the quick! This works wonderfully. 🙇
