### ISSUE TITLE
:subscription_key mandatory in gem but not in API?

### ISSUE THREAD

**Issue by lwu** [api-ai/api-ai-ruby#6]
Used this gem over the weekend and noticed that the gem seems to mandate both :client_access_token and :subscription_key as accessors But the API.ai web endpoint doesn't actually seem to require the former, that is     

:subscription_key => ENV["APIAI_SUBSCRIPTION_KEY"] # in api_ai.rb

Should the validation not enforce this as mandatory?

**Comment by Gugic** [comment]
You probably use some other package.

This package called "api-ai-ruby" and even have no file api_ai.rb inside.

We used to have subscription_key property before (because api.ai has it) but now it is not required.

**Comment by lwu** [comment]
Ah sorry I was talking about sample code which had a api_ai.rb and used require 'api-ai-ruby'.

Note that client.rb errors with Credentials missing if you don't have subscription_key:

https://github.com/api-ai/api-ai-ruby/blob/master/lib/api-ai-ruby/client.rb#L54

**Comment by Gugic** [comment]
Yes it was removed in https://github.com/api-ai/api-ai-ruby/commit/ab9880884ef7fdc3c94fb87a4b362618f990308a

Before that, subscription key was mandatory at api.ai

**Comment by lwu** [comment]
Got it thanks--maybe I just accidentally used an old gem version via Bundler and didn't realize the code had been fixed. Thanks for the library!

**Comment by Gugic** [comment]
You're welcome.
